name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Get Dependencies
      run: go get ./...
      
    - name: Build Darwin
      run:  CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o build/gfile-macos main.go
    
    - name: Build Linux 
      run:  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-w -extldflags "-static"' -o build/gfile-linux-x86_64 main.go
    
    - name: Build Windows
      run:  CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o build/gfile-win-amd64.exe main.go
      
    - name: Test
      run: go test -short ./...
